### ISSUE TITLE
Terraform setup takes longer than it should because of timeout setting

### ISSUE THREAD

**Issue by vielmetti** [OpenStackSanDiego/ServiceChains#1]
As described:

* Timeouts in the Packet/Terraform provisioner code prevent more than 8 at a time from being spun up. Workaround is to re-run Terraform every hour upping the limit from 8 to 16 to 24 to 32 to 40. (Need to budget 4 hours to spin up the environment)

The relevant code is the function at

https://github.com/hashicorp/terraform/blob/master/builtin/providers/packet/resource_packet_device.go#L261

**Comment by vielmetti** [comment]
https://twitter.com/kristofrennen/status/829975958178451456 is an example of spinning up 10 resources in parallel (the example is from Azure, but the code should port nicely).

**Comment by vielmetti** [comment]
![image](https://cloud.githubusercontent.com/assets/35047/25101777/973f5d50-2383-11e7-8842-b4cf216ce95b.png)

**Comment by vielmetti** [comment]
Here's sample DC/OS setup code that uses a count loop to set up things in parallel, from Packet:

https://www.packet.net/developers/guides/mesos-dcos-with-terraform/

**Comment by vielmetti** [comment]
more examples:

https://dcos.io/docs/1.9/administration/installing/cloud/packet/

https://github.com/dcos/packet-terraform

**Comment by johnstudarus** [comment]
That's how the instances are being spun up and they definitely do spin up in parallel but only up to a certain limit. There seems to be some sort of cap (on an API I'm going to guess) that limits how many in parallel can start. It seems to be around 6.

**Comment by johnstudarus** [comment]
For the time being, I've created a script (go.sh) which spins up physical machines 8 at a time. This issue should be bumped up to the Packet API team if there is a desire to truly get it addressed.
